### Criar nova campanha
POST https://localhost:7108/api/campanha/cadastrar
Content-Type: application/json

{
    "Nome": "Nome da Campanha",
    "Sinopse": "Texto explicando a campanha"
}


### Listar todos as campanhas
GET https://localhost:7108/api/campanha/listar

### Alterar o nome de uma campanha
PUT https://localhost:7108/api/campanha/alterar/{id}
Content-Type: application/json

{
    "Nome": "Nome Alternativo",
    "Sinopse": "Texto Alternativo"
}

### Buscar uma campanha específica por id
GET https://localhost:7108/api/campanha/buscar/{id}

### Excluir uma campanha por id
DELETE https://localhost:7108/api/campanha/deletar/{id}
