### Criar novo usuário
POST https://localhost:7108/api/usuario/cadastrar
Content-Type: application/json

{
    "Nome": "Robson"
}

### Listar todos os usuários
GET https://localhost:7108/api/usuario/listar

### Alterar o nome de um usuário
PUT https://localhost:7108/api/usuario/alterar/{id}
Content-Type: application/json

{
    "Nome": "Carlos"
}

### Buscar um usuário específico por id
GET https://localhost:7108/api/usuario/buscar/{id}

### Excluir um usuário por id
DELETE https://localhost:7108/api/usuario/deletar/{id}
